config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "index", to: "pages#index"
  resources :spaceships, only: [:index, :show, :new, :create] do
    resources :journeys, only: [:create]
  end

  namespace :admin do
    resources :journeys, only: [:index, :destroy]
    resources :spaceships, only: [:index, :edit, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :user
  belongs_to :spaceship
end

app/models/spaceship.rb
class Spaceship < ApplicationRecord
  belongs_to :user
  has_many :journeys
  has_many :users
  has_one_attached :photo

  validates :name, presence: true
  validates :superficy, presence: true
  validates :localisation, presence: true
  validates :number_of_guest, presence: true
  validates :price, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :spaceships
  has_many :journeys
  has_one_attached :photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, presence: true
end

app/controllers/admin/journeys_controller.rb
class Admin::JourneysController < ApplicationController

  def index
    @journeys = policy_scope([:admin, Journey])
  end

  def destroy
    @journey = Journey.find(params[:id])
    authorize [:admin, @journey]
    @journey.destroy
    redirect_to admin_journeys_path, status: :see_other
  end

end

app/controllers/admin/spaceships_controller.rb
class Admin::SpaceshipsController < ApplicationController
  before_action :set_spaceship, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!

  def index
    @spaceships = policy_scope([:admin, Spaceship])
  end

  def edit; end

  def update
    @spaceship.update(spaceship_params)
    redirect_to admin_spaceships_path(@spaceship)
  end

  def destroy
    @spaceship.destroy
    redirect_to admin_spaceships_path, status: :see_other
  end

  private

  def set_spaceship
    @spaceship = Spaceship.find(params[:id])
    authorize [:admin, @spaceship]
  end

  def spaceship_params
    params.require(:spaceship).permit(
      :name,
      :description,
      :superficy,
      :gravity,
      :localisation,
      :number_of_guest,
      :price,
      :photo
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization
  before_action :configure_permitted_parameters, if: :devise_controller?

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController

  def create
    @spaceship = Spaceship.find(params[:spaceship_id])
    @journey = Journey.new(journey_params)
    @journey.user = current_user
    authorize [:admin, @journey]
    @journey.spaceship = @spaceship
    if @journey.save
      redirect_to admin_journeys_path
    else
      render 'spaceships/show', status: :unprocessable_entity
    end
  end

  private

  def journey_params
    params.require(:journey).permit(
      :start_date,
      :end_date,
      :spaceship_id
      )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index]

  def index
    @spaceships = Spaceship.all
  end

  def home
  end
end

app/controllers/spaceships_controller.rb
class SpaceshipsController < ApplicationController
  before_action :set_spaceship, only: [:show]
  skip_before_action :authenticate_user!, only: [:index, :show]


  def index
    @spaceships = policy_scope(Spaceship)
    if params[:query].present?
      if params[:query] == params[:query].to_i.to_s
        @spaceships = @spaceships.where("superficy = ?", params[:query].to_i)
      else
        sql_subquery = "name @@ :query
                OR localisation @@ :query"
        @spaceships = @spaceships.where(sql_subquery, query: "%#{params[:query]}%")
      end
    end
    if params[:gravity].present?
      if params[:gravity] == nil
        spaceships_path
      end
      @spaceships = @spaceships.where(gravity: params[:gravity])
    end
  end

  def show
    @journey = Journey.new
  end

  def new
    @spaceship = Spaceship.new
    authorize @spaceship
  end

  def create
    @spaceship = Spaceship.new(spaceship_params)
    @spaceship.user = current_user
    authorize @spaceship
    if @spaceship.save
      redirect_to admin_spaceships_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_spaceship
    @spaceship = Spaceship.find(params[:id])
    authorize @spaceship
  end

  def spaceship_params
    params.require(:spaceship).permit(
      :name,
      :superficy,
      :gravity,
      :localisation,
      :number_of_guest,
      :price,
      :photo,
      :description
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/journeys/index.html.erb
<div class="container-spaceship mt-4">
  <% if Journey.count == 0 %>
    <div id="create_journey">
      <p>You don't have any pending journeys</p>
      <%= link_to "+ Create your first journey", spaceships_path, class: "btn btn-primary" %>
    </div>
  <% else %>
  <p id = "ptitle"><i>Waiting for confirmation from the owner :</i></p>
    <% @journeys.each do |journey| %>
      <div class="card-product mt-3">
          <% if journey.spaceship.photo.attached? %>
            <%= cl_image_tag journey.spaceship.photo.key %>
          <% else %>
            <%= image_tag("/home/klafonta/code/Klafonta/AlexMcFly33/stellar-journeys/app/assets/images/no_spaceship.jpg") %>
          <% end %>
        <div class="card-product-infos">
          <h2><%= journey.spaceship.name %> <%= link_to "<i class='fa-solid fa-trash-can'></i>".html_safe, admin_journey_path(journey), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "link" %></h2>
          <p>Du <%= journey.start_date.strftime("%d-%m-%Y") %>  au <%= journey.end_date.strftime("%d-%m-%Y")%>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/admin/spaceships/edit.html.erb
<div class ="container">

  <%= render "shared/formupdate" %>
</div>

app/views/admin/spaceships/index.html.erb
<div>
  <% if Spaceship.count == 0 %>
    <div id="create_journey">
      <p>You don't have any registered spaceships</p>
      <%= link_to "+ Create your first spaceship", new_spaceship_path, class: "btn btn-primary" %>
    </div>
  <% else %>
    <div class="container-spaceship">
      <p id = "ptitle"><i>Your spaceship :</i></p>
      <% new_spaceship = @spaceships.sample(3) %>
        <% @spaceships.each do |spaceship| %>
          <%= link_to spaceship_path(spaceship), class: "link-cards" do%>
            <div class="card-product mt-3">
                <% if spaceship.photo.attached? %>
                    <%= cl_image_tag spaceship.photo.key %>
                  <% else %>
                    <%= image_tag("no_spaceship.jpg") %>
                <% end %>
              <div class="card-product-infos">
                <h2><%= spaceship.name %></h2>
                <%= link_to "<i class='fa-solid fa-trash-can'></i>".html_safe, admin_spaceship_path(spaceship), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "link" %> - <%= link_to "<i class='fa-solid fa-pen-to-square'></i>".html_safe, edit_admin_spaceship_path(spaceship), class: "link" %>
              </div>
            </div>
          <% end %>
        <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StellarJourneys</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;900&family=Marcellus&family=Noto+Sans+Georgian:wght@300&family=Orbitron:wght@500;700&display=swap" rel="stylesheet">
 </head>
  <body>
    <%= render 'shared/navbar' %>
      <% if params[:action] != "home" %>
        <div class="main-wrapper">
          <%= yield %>
        </div>
        <%= render "shared/footer" %>
      <% else %>
        <%= yield %>
      <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="box">
  <div class="lines">
    <div class="line"></div>
    <div class="line"></div>
    <div class="line"></div>
  </div>
<div class="home">
    <div class="text-homepage">
      <h1>Rent a spaceship.</h1>
      <h1>Discover the entire universe.</h1>
      <h1>Repeat.</h1>
      <%= link_to "Launch", index_path, class: "link" %>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="container">
  <h2 id="title-index"><i>How does it work ?</i></h2>
  <div class="card-box">
    <div class="card-index">
      <%= image_tag "searchspace.png" %>
      <h3>Search your ideal spaceship</h3>
      <p>Take the time to have a look about all the spaceships available.</p>
    </div>
    <div class="card-index">
      <%= image_tag "chose.png" %>
      <h3>Chose one and book it !</h3>
      <p>Send your request to the owner of the spaceship.</p>
    </div>
    <div class="card-index">
      <%= image_tag "spaceman.png" %>
      <h3>The world is yours</h3>
      <p>Enjoy your trip and have fun.</p>
    </div>
  </div>
  <div style="text-align: center">
    <h3 class="quote mt-5">"I rent so much beautiful spaceship, thank you Stellar Journeys" - <small>Dark Vador</small> </h3>
    <%= link_to "Book now 🚀", spaceships_path, class: "btn btn-primary", id:"book_now" %>
  </div>
</div>

<div style="background-color: #2D4E58" class="p-5 mt-5">
  <p style="color: white" id = "ptitle"><i>No idea ? Discover this spaceship...</i></p>
  <div class="container cards">
  <% new_spaceships = @spaceships.sample(3) %>
  <% new_spaceships.each do |new_spaceship| %>
    <%= link_to spaceship_path(new_spaceship), class: "link-cards" do%>
      <div class="card-trip">
        <% if new_spaceship.photo.attached? %>
          <%= cl_image_tag new_spaceship.photo.key %>
        <% else %>
          <%= image_tag("/home/klafonta/code/Klafonta/AlexMcFly33/stellar-journeys/app/assets/images/no_spaceship.jpg") %>
        <% end %>
      <div class="card-trip-infos">
        <div>
          <h2><%= new_spaceship.name %></h2>
          <p>📍<%= new_spaceship.localisation %></p>
        </div>
          <h2 class="card-trip-pricing"><%= new_spaceship.price %>€</h2>
          <img src="https://joueclub-joueclub-fr-storage.omn.proximis.com/Imagestorage/imagesSynchro/0/0/2fc2d126386412b3d43cf6e3f29628ca8ab4b902_41063493.jpeg" class="card-trip-user avatar-bordered" />
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.theatlantic.com/thumbor/wxitU7HiKaRDjAYlYL-hdzViXAE=/0x141:2781x1705/976x549/media/img/mt/2015/10/Cygnus_v3_BandW/original.jpg);">
  <div class="container">
    <h1><%=@spaceship.name%></h1>
  </div>
</div>

app/views/shared/_booking.html.erb
<div class="booking-form">
  <%= simple_form_for [@spaceship, @journey] do |f| %>
    <%= f.input :start_date, html5: true %>
    <%= f.input :end_date, html5: true %>

    <%= f.submit 'Book now ! 🚀', class: "btn btn-primary"%>
  <% end %>
</div>

app/views/shared/_filter.html.erb
<div class="row justify-content-center">
  <div class="col-sm-6 my-3">
    <%= form_with url: spaceships_path, method: :get, class: "d-flex" do %>
        <button name="button" type="submit" class="btn-cross">
          <%= link_to "<i class='fa-solid fa-xmark'></i>".html_safe, spaceships_path%>
        </button>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            id: "search",
            placeholder: "Find your Spaceship"
        %>
        <button name="button" type="submit" class="btn-hiden">
        <i class="fas fa-search"></i></button>

    <% end %>
  </div>


  <div class="col-sm-2 my-3 d-flex justify-content">
    <%= form_with url: spaceships_path, method: :get, class: "d-flex" do %>
      <%= select_tag :gravity, options_for_select([['Gravity ?'], ['All', nil], ['With', true], ['Without', false]]), class: "form-control",
        onchange: "this.form.submit();"
      %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links" >
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by Kevin, Alexis & Yoann
  </div>
</div>

app/views/shared/_form.html.erb
<div class="form">
  <%= simple_form_for(@spaceship) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :superficy %>
    <%= f.input :gravity %>
    <%= f.input :localisation %>
    <%= f.input :number_of_guest %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
    <%= f.submit 'Create a Spaceship 🚀', class: "btn btn-primary"%>
  <% end %>
  <%= link_to "Back", spaceships_path, class: "link" %>
</div>

app/views/shared/_formupdate.html.erb
<div class="form">
  <%= simple_form_for(@spaceship, url: admin_spaceship_path, method: :patch) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :superficy %>
    <%= f.input :gravity %>
    <%= f.input :localisation %>
    <%= f.input :number_of_guest %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
    <%= f.submit 'Update your Spaceship 🚀', class: "btn btn-primary"%>
  <% end %>
    <%= link_to "Back", admin_spaceships_path, class: "link" %>

</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= params[:action] == "home" ? "navbar-transparent" : "navbar-image" %>">
    <div class="container-fluid">
      <a class="navbar-brand" href="/index">
        <%= image_tag "Logo_blanc.png" %>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/index">Home</a>
            </li>
            <li class="nav-item dropdown" id="avatar">
              <%= cl_image_tag current_user.photo.key, class:"avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, aria_haspopup: "true", aria_expanded: "false" %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <div class="dropdown-item">
                  <%= link_to "Your journeys", admin_journeys_path %>
                </div>
                <div class="dropdown-item">
                  <%= link_to "Add a spaceship", new_spaceship_path %>
                </div>
                <div class="dropdown-item">
                  <%= link_to "Your spaceships", admin_spaceships_path %>
                </div>
                <div class="dropdown-divider"></div>
                <div class="dropdown-item">
                  <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } %>
                </div>
              </div>
            </li>
        </ul>
      </div>
    </div>
  </div>
<% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= params[:action] == "home" ? "navbar-transparent" : "navbar-image" %>">
    <div class="container-fluid">
      <a class="navbar-brand" href="/spaceships">
        <%= image_tag "Logo_blanc.png" %>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/spaceships">Home</a>
            </li>
            <div id="sign_in">
              <%= link_to "Sign in", new_user_session_path %><br />
            </div>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/spaceships/index.html.erb
<%= render 'shared/filter' %>

<div class="container mt-2">
  <% if @spaceships.count == 1%>
      <p id = "ptitle"><i><%= @spaceships.count %> spaceship is available :</i></p>
    <% elsif Spaceship.count > 1%>
      <p id = "ptitle"><i><%= @spaceships.count %> spaceships are available :</i></p>
    <% elsif %>
      <p id = "ptitle"><i>Sorry, no result match with your research</i></p>
  <% end %>
</div>
<div class="container cards">
  <% @spaceships.each do |spaceship| %>
    <%= link_to spaceship_path(spaceship), class: "link-cards" do%>
      <div class="card-trip">
        <% if spaceship.photo.attached? %>
          <%= cl_image_tag spaceship.photo.key %>
        <% else %>
          <%= image_tag("no_spaceship.jpg") %>
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= spaceship.name %></h2>
            <p>📍<%= spaceship.localisation %></p>
          </div>
          <h2 class="card-trip-pricing"><%= spaceship.price %>€</h2>
          <% if spaceship.user.photo.attached? %>
              <%= cl_image_tag spaceship.user.photo.key, class: "card-trip-user avatar-bordered" %>
          <% else %>
              <img class= "card-trip-user avatar-bordered" src="https://img.myloview.com/stickers/default-avatar-profile-icon-vector-social-media-user-image-700-205124837.jpg" alt="avatar">
          <% end %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/spaceships/new.html.erb
<div class="container">
  <%= render "shared/form" %>
</div>

app/views/spaceships/show.html.erb
  <div class="container">
    <div class="row" id="head-bar">
      <div class="col-sm-1">
        <div class="user-pic">
          <% if @spaceship.user.photo.attached? %>
              <%= cl_image_tag @spaceship.user.photo.key %>
          <% else %>
              <%= image_tag("avatar.jpg") %>
          <% end %></p>
        </div>
      </div>
      <div class="col-sm-4">
        <h1><%=@spaceship.name%></h1>
      </div>
  </div>


    <div class="row">
      <div class="d-flex justify-content-between">
        <div class="col-sm-8">
          <div id="box">
            <div class="col-sm-4">
              <p>Superficy : <%= @spaceship.superficy %> m²</p>
              <p>Gravity :
              <% if @spaceship.gravity? %>
                <i class='fa-regular fa-square-check'></i>
              <%else%>
                <i class='fa-regular fa-square'></i>
              <%end%>
              </p>
              <i class="fa-solid fa-rocket"></i> <%= @spaceship.localisation %>
              <i class="fa-solid fa-people-group"></i> <%= @spaceship.number_of_guest %>
              <i class="fa-solid fa-euro-sign"></i> <%= @spaceship.price %>
            </div>
            <div class="col-sm-4" id="spaceship-img">
              <p> <% if @spaceship.photo.attached? %>
                    <%= cl_image_tag @spaceship.photo.key %>
                  <% else %>
                    <%= image_tag("/home/klafonta/code/Klafonta/AlexMcFly33/stellar-journeys/app/assets/images/no_spaceship.jpg") %>
                <% end %></p>
              <div class="rating">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
              </div>
            </div>
          </div>

          <div id="row">
            <div class="box-description">
              <p>
                <%= @spaceship.description %>
              </p>
            </div>
            <div class="box-description">
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%=asset_path("Sylvain.jpg") %>" />
              <p style="vertical-align: middle"><i> "Nice ship ! Weard breathing owner..."</i> </p>
              <div class="rating">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-4 d-flex justify-content-center">
          <div class="box-booking">
            <p> <%= render "shared/booking" %></p>
          </div>
        </div>
      </div>
    </div>
  </div>